name: buku_saku
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # display PDF
#  flutter_pdfview: ^1.0.4

  # path
#  file_picker: ^2.1.6
  path: ^1.7.0
  path_provider: ^2.0.8
#  audioplayers: ^0.20.1

  http: ^0.13.4
  email_validator: ^2.0.1
  shared_preferences: ^2.0.15
  get: ^4.6.5
  collapsible_app_bar: ^0.1.2
  ftpconnect: ^0.1.9
  image_picker: ^0.8.6
  flutter_native_image: ^0.0.6+1
  flutter_image_compress: ^1.1.3


  # load from Firebase
#  firebase_core: ^0.7.0
#  firebase_storage: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/